#include "global.h"
#include "mf_theme_groups.h"
#include "constants/opponents.h"

#if MF_RANDOMIZER

struct MfThemeMember
{
    u16 trainerId;
    u8 group;
};

// Trainers who appear on Kanto gym / E4 / Champion maps (not Dojo, not Rocket).
static const struct MfThemeMember sMfThemeMembers[] =
{
    // Pewter
    { TRAINER_LEADER_BROCK,        MF_THEME_GROUP_GYM_PEWTER },
    { TRAINER_CAMPER_LIAM,         MF_THEME_GROUP_GYM_PEWTER },
    // Cerulean
    { TRAINER_LEADER_MISTY,        MF_THEME_GROUP_GYM_CERULEAN },
    { TRAINER_PICNICKER_DIANA,     MF_THEME_GROUP_GYM_CERULEAN },
    { TRAINER_SWIMMER_MALE_LUIS,   MF_THEME_GROUP_GYM_CERULEAN },
    // Vermilion
    { TRAINER_LEADER_LT_SURGE,     MF_THEME_GROUP_GYM_VERMILION },
    { TRAINER_SAILOR_DWAYNE,       MF_THEME_GROUP_GYM_VERMILION },
    { TRAINER_ENGINEER_BAILY,      MF_THEME_GROUP_GYM_VERMILION },
    { TRAINER_GENTLEMAN_TUCKER,    MF_THEME_GROUP_GYM_VERMILION },
    // Celadon
    { TRAINER_LEADER_ERIKA,        MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_LASS_KAY,            MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_LASS_LISA,           MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_PICNICKER_TINA,      MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_BEAUTY_BRIDGET,      MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_BEAUTY_TAMIA,        MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_BEAUTY_LORI,         MF_THEME_GROUP_GYM_CELADON },
    { TRAINER_COOLTRAINER_MARY,    MF_THEME_GROUP_GYM_CELADON },
    // Fuchsia
    { TRAINER_LEADER_KOGA,         MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_TAMER_PHIL,          MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_TAMER_EDGAR,         MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_JUGGLER_KIRK,        MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_JUGGLER_SHAWN,       MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_JUGGLER_KAYDEN,      MF_THEME_GROUP_GYM_FUCHSIA },
    { TRAINER_JUGGLER_NATE,        MF_THEME_GROUP_GYM_FUCHSIA },
    // Saffron gym (not Dojo)
    { TRAINER_LEADER_SABRINA,      MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_PSYCHIC_JOHAN,       MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_PSYCHIC_TYRON,       MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_PSYCHIC_CAMERON,     MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_PSYCHIC_PRESTON,     MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_CHANNELER_AMANDA,    MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_CHANNELER_STACY,     MF_THEME_GROUP_GYM_SAFFRON },
    { TRAINER_CHANNELER_TASHA,     MF_THEME_GROUP_GYM_SAFFRON },
    // Cinnabar
    { TRAINER_LEADER_BLAINE,       MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_SUPER_NERD_ERIK,     MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_SUPER_NERD_AVERY,    MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_SUPER_NERD_DEREK,    MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_SUPER_NERD_ZAC,      MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_BURGLAR_QUINN,       MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_BURGLAR_RAMON,       MF_THEME_GROUP_GYM_CINNABAR },
    { TRAINER_BURGLAR_DUSTY,       MF_THEME_GROUP_GYM_CINNABAR },
    // Viridian gym (not Rocket hideout / Silph Giovanni)
    { TRAINER_LEADER_GIOVANNI,     MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_TAMER_JASON,         MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_TAMER_COLE,          MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_BLACK_BELT_ATSUSHI,  MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_BLACK_BELT_KIYO,     MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_BLACK_BELT_TAKASHI,  MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_COOLTRAINER_SAMUEL,  MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_COOLTRAINER_YUJI,    MF_THEME_GROUP_GYM_VIRIDIAN },
    { TRAINER_COOLTRAINER_WARREN,  MF_THEME_GROUP_GYM_VIRIDIAN },
    // Elite Four (first + rematch)
    { TRAINER_ELITE_FOUR_LORELEI,  MF_THEME_GROUP_E4_LORELEI },
    { TRAINER_ELITE_FOUR_LORELEI_2, MF_THEME_GROUP_E4_LORELEI },
    { TRAINER_ELITE_FOUR_BRUNO,    MF_THEME_GROUP_E4_BRUNO },
    { TRAINER_ELITE_FOUR_BRUNO_2,  MF_THEME_GROUP_E4_BRUNO },
    { TRAINER_ELITE_FOUR_AGATHA,   MF_THEME_GROUP_E4_AGATHA },
    { TRAINER_ELITE_FOUR_AGATHA_2, MF_THEME_GROUP_E4_AGATHA },
    { TRAINER_ELITE_FOUR_LANCE,    MF_THEME_GROUP_E4_LANCE },
    { TRAINER_ELITE_FOUR_LANCE_2,  MF_THEME_GROUP_E4_LANCE },
    // Champion Blue (all starter variants, first + rematch)
    { TRAINER_CHAMPION_FIRST_SQUIRTLE,     MF_THEME_GROUP_CHAMPION },
    { TRAINER_CHAMPION_FIRST_BULBASAUR,    MF_THEME_GROUP_CHAMPION },
    { TRAINER_CHAMPION_FIRST_CHARMANDER,   MF_THEME_GROUP_CHAMPION },
    { TRAINER_CHAMPION_REMATCH_SQUIRTLE,   MF_THEME_GROUP_CHAMPION },
    { TRAINER_CHAMPION_REMATCH_BULBASAUR,  MF_THEME_GROUP_CHAMPION },
    { TRAINER_CHAMPION_REMATCH_CHARMANDER, MF_THEME_GROUP_CHAMPION },
};

u8 MfTrainerThemeGroup(u16 trainerNum)
{
    u16 i;

    if (trainerNum == TRAINER_NONE)
        return MF_THEME_GROUP_NONE;

    for (i = 0; i < ARRAY_COUNT(sMfThemeMembers); i++)
    {
        if (sMfThemeMembers[i].trainerId == trainerNum)
            return sMfThemeMembers[i].group;
    }
    return MF_THEME_GROUP_NONE;
}

#else // !MF_RANDOMIZER

u8 MfTrainerThemeGroup(u16 trainerNum)
{
    (void)trainerNum;
    return MF_THEME_GROUP_NONE;
}

#endif // MF_RANDOMIZER
